#!/bin/bash

id=$(echo $[($RANDOM % ($[10000 - 32000] + 1)) + 10000] )
echo "$id"

yad --text-info --text="WARNING IF YOU USE PROTON OR WINE THE PERFORMANCE DEPENDS OF THERMAL, OPENGL AND VULKAN DRIVERS, LINUX KERNEL AND THERMAL MANAGEMENT , BACKGORUND PROCESSES MAY CAUSE BUGS. see more info in: https://wiki.winehq.org/PerformanceS" --title="WARNING"


yad --plug="$id" --tabnum=1 --form \
--text="System" \
--field="<b>Update keyring</b>":FBTN "konsole -e 'sudo pacman -S archlinux-keyring --noconfirm'" \
--field="<b>Refresh Mirrors</b>":FBTN "konsole -e 'sudo reflector --verbose -l 20 --sort rate --save /etc/pacman.d/mirrorlist'" \
--field="<b>System Updates</b>":FBTN "konsole  -e 'sudo pacman -Syyu --noconfirm'" \
--field="<b>Aur Updates</b>":FBTN "konsole -e 'yay -Syyu --noconfirm'" \
--field="<b>Install Teamviewer</b>":FBTN "konsole -e 'sudo pacman -S teamviewer --noconfirm'" \
--field="<b>Launch TeamViewer for remote support</b>":FBTN "konsole -e '/opt/teamviewer/tv_bin/script/teamviewer'" \
--field="<b>Install yay (aur package manager) </b>":FBTN "konsole -e bash -c 'cd /tmp && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si --noconfirm'" &
--field="<b>Add Chaotic-AUR</b>":FBTN "konsole -e bash -c ''"


yad --plug="$id" --tabnum=2 --form \
--text="Games" \
--field="<b>Install Steam client</b>":fbtn "konsole -e 'sudo pacman -S --noconfirm steam-native-runtime gamemode'" \
--field="<b>Install Heroic Launcher (a unofficial epic games launcher)</b>":fbtn "konsole -e 'yay -S --noconfirm heroic-games-launcher-bin gamemode'" \
--field="<b>Install Lutris Launcher (a game manager including for install games with Wine)</b>":fbtn "konsole -e 'sudo pacman -S --noconfirm lutris gamemode'" \
--field="<b>Install ProtonGE Updater (a Proton Compatibility Layer Updater</b>":fbtn "konsole -e 'yay -S --noconfirm proton-community-updater'" \
--field="<b>Install MangoHUD</b>":fbtn "konsole -e 'yay -S --noconfirm mangohud goverlay-bin'" \
--field="<b>Install Bottles (A Wine prefixes manager)</b>":fbtn "konsole -e 'yay -S --noconfirm bottles'" &



yad --plug="$id" --tabnum=3 --form \
--text="Daemons" \
--field="<b>Enable Cups/Printer</b>":fbtn "konsole -e 'systemctl enable --now cups'" \
--field="<b>Cups/Printer Web Interface</b>":fbtn "xdg-open http://127.0.0.1:631" \
--field="<b>Enable TeamViewer Daemon</b>":FBTN "konsole -e ' teamviewer --daemon start'" &


yad --notebook --key="$id" --center --tab-pos=top --width=480 --height=175 --tab "<b>(1).Welcome to uarchutil!</b>" --tab="<b>(2).System</b>" --tab="<b>(3). Daemons</b>" \
--title="Universal Arch Linux Utilities Program v1.0.0" \
--justify=center &

case $? in
    0)
    exit;;
    1)
    exit;;
    70)
    exit;;
    252)
    exit;;
esac
