#!/bin/bash
# Forked and Inspired by Xerolinux-Tool

id=$(echo $[($RANDOM % ($[10000 - 32000] + 1)) + 10000] )
echo "$id"

zenity --info --text="WARNING IF YOU USE PROTON OR WINE THE PERFORMANCE DEPENDS OF THERMAL, OPENGL AND VULKAN DRIVERS, LINUX KERNEL AND THERMAL MANAGEMENT , BACKGORUND PROCESSES MAY CAUSE BUGS. see more info in: https://wiki.winehq.org/PerformanceS" --title="WARNING"


yad --plug="$id" --tabnum=1 --form \
--field="<b>Step 1. Refresh Mirrors</b>":FBTN "konsole -e 'sudo reflector --verbose -l 20 --sort rate --save /etc/pacman.d/mirrorlist'" \
--field="<b>Step 2. System Updates</b>":FBTN "konsole  -e 'sudo pacman -Syyu --noconfirm'" \
--field="<b>Step 3. Aur Updates</b>":FBTN "konsole -e 'yay -Syyu --noconfirm'" \
--field="<b>Step 4. (Optional) Arch Keyring Updater</b>":FBTN "konsole -e 'sudo pacman -S archlinux-keyring --noconfirm'" \
--field="<b>Step 5. Install Teamviewer</b>":FBTN "konsole -e 'sudo pacman -S teamviewer --noconfirm'" \
--field="<b>Step 6. Activate Teamviewer daemon for remote access</b>":FBTN "konsole -e ' teamviewer --daemon start'" \
--field="<b>Step 7. Launch Teamviewer for Remote Support</b>":FBTN "konsole -e '/opt/teamviewer/tv_bin/script/teamviewer'" \
--field="<b>Step 8. Install Warpinator to share between computers in your local network</b>":FBTN "konsole -e 'sudo pacman -S warpinator --noconfirm'" \
--field="<b>Step 9. Launch Warpinator</b>":FBTN "konsole -e  'warpinator'" \
--field="<b>Step 10. Incase warpinator leaves a terminal open click this. </b>":FBTN "konsole -e  'killall warpinator'" \
--field="<b>Step extra. Install YAY</b>":fbtn "konsole -e bash -c 'cd /tmp && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si --noconfirm'" &



yad --plug="$id" --tabnum=2 --form \
--field="<b>Install Steam Native</b>":fbtn "konsole -e 'sudo pacman -S --noconfirm steam-native-runtime gamemode'" \
--field="<b>Install Heroic Launcher</b>":fbtn "konsole -e 'yay -S --noconfirm heroic-games-launcher-bin gamemode'" \
--field="<b>Install Lutris Launcher</b>":fbtn "konsole -e 'sudo pacman -S --noconfirm lutris gamemode'" \
--field="<b>Install ProtonGE Updater</b>":fbtn "konsole -e 'yay -S --noconfirm proton-community-updater'" \
--field="<b>Install Mangohud/Goverlay</b>":fbtn "konsole -e 'yay -S --noconfirm mangohud goverlay-bin'" \
--field="<b>Install Bottles Launcher</b>":fbtn "konsole -e 'yay -S --noconfirm bottles'" &



yad --plug="$id" --tabnum=3 --form \
--field="<b>Step 1.Enable Cups/Printer</b>":fbtn "konsole -e 'systemctl enable --now cups'" \
--field="<b>Step 2. Cups/Printer Web Interface</b>":fbtn "xdg-open http://127.0.0.1:631" &



yad --notebook --key="$id" --center --tab-pos=top --width=480 --height=175 --tab "<b>(1).Welcome</b>" --tab="<b>(2).Maintenance and Updates and Support</b>" --tab="<b>(3).Game Program Installers</b>" --tab="<b>(4). Cups/Printer Installation</b>" \
--title="Universal Arch Linux Utilities Program v1.0.0" \
--justify=center \

case $? in
    0)
    exit;;
    1)
    exit;;
    70)
    exit;;
    252)
    exit;;
esac
